version: '3.3'

networks:
  football-rental-network:
    external: true

services:
  server:
    container_name: football-rental
    image: fizzmod/football-rental:${TAG:-local}
    build: .
    volumes:
      - .:/var/www/janis
      - ~/.aws:/root/.aws
    environment:
      - NODE_ENV=dev
      - MICROSERVICE=alarm
    ports:
      - "3000:3000"
    networks:
      - football-rental-network

    command: "sls offline -P 3000 -o 0.0.0.0 -p api --printOutput --noAuth --useSeparateProcesses"

  mongo:
    container_name: football-rental-mongo
    image: mongo:3.6
    volumes:
      - ~/.mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - football-rental-network
