service: football-rental

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-east-1

functions:

  users:
    handler: handler.users
    events:
      - http:
          path: users
          method: ANY

custom:
  tableNames:
    users: users

plugins:
  - serverless-offline

resources:

  Resources:

    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableNames.users}
        Tags:
          - Key: Service
            Value: ${self:service}
